---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pssp-prod-api-deployment
  labels:
    app: pssp-prod-api
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pssp-prod-api
  template:
    metadata:
      labels:
        app: pssp-prod-api
        env: prod
    spec:
      containers:
        - name: pssp-prod-api
          image: wallen/pssp-app-api:${TAG}
          imagePullPolicy: Always
          env:
          - name: REDIS_IP
            value: ${RIP}
          ports:
          - name: http
            containerPort: 5000
