---
version: '3'
services:
    wallen-db:
        image: redis:6.2.3
        container_name: wallen-db
        ports:
            - 6441:6379
        user: "827385:815499"
        volumes:
            - ./data/:/data/
    wallen-api:
        build:
            context: ../
            dockerfile: ${PWD}/docker/Dockerfile.api
        container_name: wallen-api
        environment:
            - REDIS_IP=wallen-db
        ports:
            - 5041:5000
        depends_on:
            - wallen-db
    wallen-wrk:
        build:
            context: ../ 
            dockerfile: ${PWD}/docker/Dockerfile.wrk
        container_name: wallen-wrk
        environment:
            - REDIS_IP=wallen-db
        depends_on:
            - wallen-db
