FROM python:3.6.13

RUN git clone https://github.com/realbigws/Predict_Property && \
    cd Predict_Property/source_code && \
    make

RUN pip3 install hotqueue==0.2.8 \
                 matplotlib==3.3.4 \
                 redis==3.5.3 

COPY ./src/worker.py /app/
WORKDIR /app

CMD ["python", "/app/worker.py"]
